# Generated by Django 4.2.8 on 2024-12-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
